config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "messages#index"
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :group
  validates :body_or_image, presence: true
  validates :group_id, presence: true
  validates :user_id, presence: true

  private

  def body_or_image
    body.present? || image.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages

  scope :search, -> (keyword){ where("name LIKE(?)", "%#{ keyword }%") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_strong_parameter, if: :devise_controller?

  private

  def configure_strong_parameter
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :group_find, only: [:edit, :update]

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = "グループを作成しました"
      redirect_to group_messages_path(@group.id)
    else
      flash.now[:alert] = "グループを作成できませんでした"
      render "new"
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      flash[:notice] = "グループを編集しました"
      redirect_to group_messages_path(params[:id])
    else
      flash.now[:alert] = "グループを編集できませんでした"
      render "edit"
    end
  end

  private

  def group_find
    @group = Group.find(params[:id])
    @users = @group.users
  end

  def group_params
    params.require(:group).permit(:name, { user_ids: [] })
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_group, only: [:index, :create]
  before_action :group_messages, only: [:index, :create]

  def index
    @message = Message.new
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = @group.messages.new(message_params)

    if @message.save
      respond_to do |format|
        format.html {
         redirect_to group_messages_path(params[:group_id]), notice: "メッセージを作成しました"
        }
        format.json {
          render "create", handlers: "jbuilder"
        }
      end
    else
      flash.now[:alert] = "メッセージ作成に失敗しました"
      render "index"
    end
  end

  private

  def find_group
    @group = Group.find(params[:group_id]) if params[:group_id]
  end

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def group_messages
    @messages = @group.messages.includes(:user).order("created_at ASC") if params[:group_id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update]

  def index
    @users = User.search params[:keyword]
    respond_to do |format|
      format.json
    end
  end

  def edit
  end

  def update
    @user.update(user_parameter)

    if @user.save
      redirect_to root_path
    else
      redirect_to edit_user_path(current_user.id)
    end
  end

  private

  def user_parameter
    params.require(:user).permit(:name, :email)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def new_or_edit_add
    if current_page?(controller: "groups", action: "new")
      content_tag(:h1, "新規チャットグループ")
    else
      content_tag(:h1, "チャットグループ編集")
    end
  end

  def message_check(group)
    if group.messages.empty?
      "まだメッセージはありません"
    elsif group.messages.last.body.present?
      group.messages.last.body
    else
      "画像が投稿されています"
    end
  end
end

app/views/groups/_form.haml
= new_or_edit_add
= form_for group, html: {"accept-charset" => "UTF-8", class: "edit_chat_group", class: "new_chat_group", id: "edit_chat_group_#{group.id}"} do |f|
  .chat-group-form__errors
    %h2
      - if group.errors.any?
        #{group.errors.count}件のエラーが発生しました。
        %ul
        - group.errors.full_messages.each do |msg|
          %li #{msg}
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input", id: "chat_group_name", value: group.name

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label "チャットメンバー", class: "chat-group-form__label"

    .chat-group-form__field--right
      .chat-group-user.clearfix.js-chat-member#chat-group-user-8
      %ul#chat-group-users
        %li.chat-group-user.clearfix
          %input{ name: "group[user_ids][]", type: "hidden", value: "#{current_user.id}" }
          %p.chat-group-user__name
            = current_user.name
        - @users.each do |user|
          - if user != current_user
            %li.chat-group-user.clearfix
              %input{ name: "group[user_ids][]", type: "hidden", value: "#{user.id}" }
              %p.chat-group-user__name
                = user.name
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label{ class: "chat-group-form__label", for: "user-search-field" }
        チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input{ class: "chat-group-form__input", id: "user-search-field", placeholder: "追加したいユーザー名を入力してください", type: "text" }
      #user-search-result
      = f.submit "Save", class: "chat-group-form__action-btn"

app/views/groups/_groups.haml
- groups.each do|group|
  .side__groups__group
    .side__groups__group__name
      = link_to group.name, group_messages_path(group)
    .side__groups__group__message
      = message_check(group)

app/views/groups/edit.html.haml
.chat-group-form
  = render partial: "form", locals: { group: @group }

app/views/groups/new.html.haml
.chat-group-form
  = render partial: "form", locals: { group: @group }

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/flash"
    = yield

app/views/messages/index.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
  %body
    .side
      .side__menu
        .side__menu__user-name
          = current_user.name
        .side__menu__right-content
          %a{class: "side_menu__right-content__new-group", href: new_group_path}
            %i.fa.fa-pencil-square-o.side_menu__right-content__new-group__icon
          %a{class: "edit_user_path(current_user.id)side__menu__right-content__edit-account", href: "#{edit_user_path(current_user.id)}"}
            %i.fa.fa-cog.side__menu__right-content__edit-account__icon
      .side__groups
        = render partial: "groups/groups", locals: {groups: current_user.groups}

  - if @group
    .main
      %header.main__header
        .main__header__left-content
          .main__header__left-content__group-name
            = @group.name
          .main__header__left-content__group-members
            Members:
            - @group.users.each do |user|
              = user.name
        = link_to "Edit", edit_group_path(@group) , class: "main__header__group-edit--frame-blue"

      .main__chat
        - @messages.each do |message|
          .main__chat__message
            .main__chat__message__user-name
              = message.user.name
            .main__chat__message__send-time
              = message.created_at.strftime("%Y/%m/%d %H:%M:%S")
            .main__chat__message__text
              = message.body if message.body
            .main__chat__message__image
              = image_tag message.image if message.image

      %footer.main__footer
        .main__footer__message-form
          = form_for [@group, @message], html: { class: "js-form" } do |f|
            =f.text_field :body, class: "main__footer__message-form__text", placeholder: "type a message"
            = f.label :image, { class: "fa fa-picture-o", for: "file_field" } do
              = f.file_field :image, style: "display: none;", id: "file_field"
            =f.submit "Send", class: "main__footer__message-form__submit--back-blue"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(@user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'